<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="4" failed="2" skipped="2">
  <reporter-output>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Sorry your TC is failed]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[P is running ]]>
    </line>
    <line>
      <![CDATA[Congarts your TC is passed]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Q is running]]>
    </line>
    <line>
      <![CDATA[Congarts your TC is passed]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Your TC is Skipped, please check]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[TC2 is running]]>
    </line>
    <line>
      <![CDATA[Congarts your TC is passed]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Sorry your TC is failed]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Tc is running ]]>
    </line>
    <line>
      <![CDATA[Congarts your TC is passed]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Your TC is Skipped, please check]]>
    </line>
  </reporter-output>
  <suite started-at="2022-04-02T01:11:10 IST" name="Suite" finished-at="2022-04-02T01:11:10 IST" duration-ms="160">
    <groups>
    </groups>
    <test started-at="2022-04-02T01:11:10 IST" name="Test" finished-at="2022-04-02T01:11:10 IST" duration-ms="160">
      <class name="listener.Testing1">
        <test-method signature="TC3()[pri:0, instance:listener.Testing1@3c7f66c4]" started-at="2022-04-02T01:11:10 IST" name="TC3" finished-at="2022-04-02T01:11:10 IST" duration-ms="15" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at listener.Testing1.TC3(Testing1.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Your TC is started]]>
            </line>
            <line>
              <![CDATA[Sorry your TC is failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC3 -->
        <test-method signature="TC2()[pri:0, instance:listener.Testing1@3c7f66c4]" started-at="2022-04-02T01:11:10 IST" name="TC2" finished-at="2022-04-02T01:11:10 IST" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Your TC is started]]>
            </line>
            <line>
              <![CDATA[TC2 is running]]>
            </line>
            <line>
              <![CDATA[Congarts your TC is passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC2 -->
        <test-method signature="TC4()[pri:0, instance:listener.Testing1@3c7f66c4]" started-at="2022-04-02T01:11:10 IST" name="TC4" finished-at="2022-04-02T01:11:10 IST" depends-on-methods="listener.Testing1.TC3" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Testing1.TC4()[pri:0, instance:listener.Testing1@3c7f66c4] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Testing1.TC4()[pri:0, instance:listener.Testing1@3c7f66c4] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[Your TC is Skipped, please check]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC4 -->
        <test-method signature="Tc1()[pri:0, instance:listener.Testing1@3c7f66c4]" started-at="2022-04-02T01:11:10 IST" name="Tc1" finished-at="2022-04-02T01:11:10 IST" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Your TC is started]]>
            </line>
            <line>
              <![CDATA[Tc is running ]]>
            </line>
            <line>
              <![CDATA[Congarts your TC is passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- Tc1 -->
      </class> <!-- listener.Testing1 -->
      <class name="listener.Testing2">
        <test-method signature="R()[pri:0, instance:listener.Testing2@4fb3ee4e]" started-at="2022-04-02T01:11:10 IST" name="R" finished-at="2022-04-02T01:11:10 IST" duration-ms="19" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at listener.Testing2.R(Testing2.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Your TC is started]]>
            </line>
            <line>
              <![CDATA[Sorry your TC is failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- R -->
        <test-method signature="Q()[pri:0, instance:listener.Testing2@4fb3ee4e]" started-at="2022-04-02T01:11:10 IST" name="Q" finished-at="2022-04-02T01:11:10 IST" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Your TC is started]]>
            </line>
            <line>
              <![CDATA[Q is running]]>
            </line>
            <line>
              <![CDATA[Congarts your TC is passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- Q -->
        <test-method signature="P()[pri:0, instance:listener.Testing2@4fb3ee4e]" started-at="2022-04-02T01:11:10 IST" name="P" finished-at="2022-04-02T01:11:10 IST" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Your TC is started]]>
            </line>
            <line>
              <![CDATA[P is running ]]>
            </line>
            <line>
              <![CDATA[Congarts your TC is passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- P -->
        <test-method signature="S()[pri:0, instance:listener.Testing2@4fb3ee4e]" started-at="2022-04-02T01:11:10 IST" name="S" finished-at="2022-04-02T01:11:10 IST" depends-on-methods="listener.Testing2.R" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Testing2.S()[pri:0, instance:listener.Testing2@4fb3ee4e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Testing2.S()[pri:0, instance:listener.Testing2@4fb3ee4e] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[Your TC is Skipped, please check]]>
            </line>
          </reporter-output>
        </test-method> <!-- S -->
      </class> <!-- listener.Testing2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
